# Use Debian Slim as the base image
FROM debian:stable-slim

# Set environment variables
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 PATH=/opt/conda/bin:$PATH

# Install necessary dependencies
RUN apt-get update && apt-get install -y \
    curl \
    bzip2 \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Download and install Miniconda
RUN curl -L -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    /bin/bash miniconda.sh -b -p /opt/conda && \
    rm miniconda.sh
    # /opt/conda/bin/conda clean -afy

# Copy the environment.yml file into the Docker image
COPY environment.yml /tmp/environment.yml

# Create the conda environment using the environment.yml file
RUN /opt/conda/bin/conda env create -f /tmp/environment.yml && \
    conda clean -afy && \
    rm -rf /opt/conda/pkgs/* /tmp/environment.yml

# Activate the conda environment
SHELL ["/bin/bash", "-c"]
RUN echo "source activate DENV_PHYLO" > ~/.bashrc
ENV SHELL=/bin/bash \
    CONDA_DEFAULT_ENV=DENV_PHYLO \
    PATH=/opt/conda/envs/DENV_PHYLO/bin:$PATH

# Set entrypoint to use bash
ENTRYPOINT ["/bin/bash"]
